import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { Toaster } from "sonner";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Swam Htet Aung - Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased font-sora`}>
        {/* <Layout>{children}</Layout> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
